# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a0a47a385bb1f2b9a78e647ec6ff5eebcc6547ee6a600966fe0f5c35c4a37f9db10414d17283446e4391e18a360cba2f9828050eef1aa49bfbd74f513a32ae7

test:
  secret_key_base: 9346b1ce3fdad0fabb674a5ee9f5a05455e9be3e5655efc0f1a40cf4a000dae0dc9f579ae12acd822c5362e7095d5502ab79cf2e60fbd81e3c97fc7769a5dcc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
